# Funding options for SetuPranali
# These are displayed on the GitHub repository page

github: [setupranali]
# patreon: universalbi
# open_collective: setupranali
# ko_fi: universalbi
# custom: ['https://setupranali.io/sponsor']

